import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowRight, BriefcaseBusiness, CheckCircle2, Code2, Lightbulb, Wrench } from "lucide-react";
import { careers, projects, resources, roadmapPhases } from "@/lib/content";
import "../../detail.css";

export default async function Page({params}:{params:Promise<{slug:string}>}) {
  const {slug}=await params; const career=careers.find(c=>c.slug===slug); if(!career) notFound();
  const relatedProjects=projects.filter(p=>p.career===career.name).slice(0,3);
  return <><section className="detail-hero"><div className="container"><Link href="/careers">← All career paths</Link><div className="detail-title"><span className="detail-icon"><Code2/></span><div><span className="pill">{career.category}</span><h1>{career.name}</h1><p>{career.description} Expectations vary across companies and individual positions.</p></div></div><button className="btn btn-primary">Add to my interests</button></div></section>
  <div className="container detail-layout"><article className="detail-main">
    <section><span className="eyebrow">Role overview</span><h2>What the role is</h2><p>{career.name} professionals turn ambiguous needs into reliable technical outcomes. The work typically blends design, implementation, review, testing, and communication with teammates and stakeholders.</p><div className="info-grid">{[["Responsibilities","Plan work, build systems, review changes, investigate issues, and document decisions."],["Common tools",career.tools.join(", ")],["Interview emphasis",`${career.algorithms} algorithm preparation; role-specific practical questions are also common.`],["Project emphasis","Show evidence of decisions, testing, iteration, and an outcome—not just a list of features."]].map(([a,b])=><div className="card" key={a}><strong>{a}</strong><p>{b}</p></div>)}</div></section>
    <section><span className="eyebrow">Skills to learn</span><h2>Build capability in layers.</h2><div className="skill-list">{["Programming fluency and debugging","Data structures and tradeoffs","Testing and dependable delivery","Collaboration with Git","Clear technical communication"].map((s,i)=><div key={s}><span>{i+1}</span><div><strong>{s}</strong><p>{i<2?"Learn concepts through small, testable exercises, then use them inside a project.":"Practice the workflow on real work and write down what changed because of your decision."}</p></div></div>)}</div></section>
    <section><span className="eyebrow">Beginner roadmap</span><h2>From foundations to applications.</h2><div className="compact-roadmap">{roadmapPhases.slice(0,8).map((p)=><div key={p[0]}><span>{p[0]}</span><strong>{p[1]}</strong><small>{p[3]}</small></div>)}</div><Link className="btn btn-secondary" href="/roadmaps">Open interactive roadmap <ArrowRight size={16}/></Link></section>
    <section><span className="eyebrow">Portfolio evidence</span><h2>Recommended projects</h2>{relatedProjects.length?<div className="info-grid">{relatedProjects.map(p=><Link href={`/projects/${p.slug}`} className="card linked-card" key={p.slug}><Lightbulb/><strong>{p.title}</strong><p>{p.description}</p></Link>)}</div>:<p className="empty">Explore the project library and filter by tools used in this path.</p>}</section>
  </article><aside className="detail-aside"><div className="card"><h2>At a glance</h2><dl><div><dt>Beginner friendliness</dt><dd>{career.friendliness}</dd></div><div><dt>Math intensity</dt><dd>{career.math}</dd></div><div><dt>Algorithm prep</dt><dd>{career.algorithms}</dd></div></dl></div><div className="card"><h2>Search titles</h2>{[`${career.name} Intern`,`Junior ${career.name}`,`Associate ${career.name}`,`New Grad ${career.name}`].map(t=><span className="aside-item" key={t}><BriefcaseBusiness size={14}/>{t}</span>)}</div><div className="card"><h2>Useful starting points</h2>{resources.slice(0,4).map(r=><a className="aside-item" href={r.url} target="_blank" rel="noopener noreferrer" key={r.url}><Wrench size={14}/>{r.title}</a>)}</div><div className="card notice"><CheckCircle2/><p>Job descriptions are wish lists, not universal rules. Look for the core work and show relevant evidence.</p></div></aside></div></>
}
