"use client";

import Link from "next/link";
import { useMemo, useState } from "react";
import { ArrowRight, Bookmark, BriefcaseBusiness, CheckCircle2, Clock3, Code2, ExternalLink, MessageCircle, Search, SlidersHorizontal, Star } from "lucide-react";
import { careers, discussions, projects, resources, roadmapPhases } from "@/lib/content";
import "./explorers.css";

function Hero({eyebrow,title,description}:{eyebrow:string;title:string;description:string}) {
  return <section className="page-hero"><div className="container"><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{description}</p></div></section>;
}

function FilterBar({query,setQuery,placeholder,category,setCategory,categories}:{query:string;setQuery:(s:string)=>void;placeholder:string;category:string;setCategory:(s:string)=>void;categories:string[]}) {
  return <div className="filter-bar card"><label className="search-field"><Search size={18}/><span className="sr-only">Search</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={placeholder}/></label><label className="select-field"><SlidersHorizontal size={17}/><span className="sr-only">Filter category</span><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{categories.map(c=><option key={c}>{c}</option>)}</select></label></div>;
}

export function CareersExplorer() {
  const [query,setQuery]=useState(""); const [category,setCategory]=useState("");
  const categories=[...new Set(careers.map(c=>c.category))];
  const filtered=useMemo(()=>careers.filter(c=>(!category||c.category===category)&&`${c.name} ${c.tools.join(" ")}`.toLowerCase().includes(query.toLowerCase())),[query,category]);
  return <><Hero eyebrow="Career explorer" title="There’s more than one way into tech." description="Compare the day-to-day work, learning curve, tools, and interview emphasis across fourteen career directions."/><section className="section-tight container"><FilterBar query={query} setQuery={setQuery} placeholder="Search careers or tools…" category={category} setCategory={setCategory} categories={categories}/><p className="result-count">{filtered.length} paths</p><div className="directory-grid">{filtered.map(c=><Link href={`/careers/${c.slug}`} className="directory-card card" key={c.slug}><div className="directory-icon"><Code2/></div><span className="pill">{c.category}</span><h2>{c.name}</h2><p>{c.description}</p><div className="metric-row"><span><small>Beginner</small><strong>{c.friendliness}</strong></span><span><small>Algorithms</small><strong>{c.algorithms}</strong></span><span><small>Math</small><strong>{c.math}</strong></span></div><div className="tag-row">{c.tools.map(t=><span className="mini-tag" key={t}>{t}</span>)}</div><span className="card-link">View career guide <ArrowRight size={16}/></span></Link>)}</div>{filtered.length===0&&<div className="empty">No paths match those filters. Try a broader search.</div>}</section></>;
}

export function ProjectsExplorer() {
  const [query,setQuery]=useState(""); const [category,setCategory]=useState("");
  const categories=[...new Set(projects.map(c=>c.difficulty))];
  const filtered=projects.filter(p=>(!category||p.difficulty===category)&&`${p.title} ${p.tech} ${p.career}`.toLowerCase().includes(query.toLowerCase()));
  return <><Hero eyebrow="Project library" title="Build projects worth talking about." description="Each brief starts with a meaningful problem and shows how to make the result more rigorous, useful, and uniquely yours."/><section className="section-tight container"><FilterBar query={query} setQuery={setQuery} placeholder="Search technologies, careers, or ideas…" category={category} setCategory={setCategory} categories={categories}/><div className="project-directory">{filtered.map(p=><article className="project-list-card card" key={p.slug}><div className="project-list-top"><span className="pill">{p.difficulty}</span><button aria-label={`Bookmark ${p.title}`}><Bookmark size={18}/></button></div><h2><Link href={`/projects/${p.slug}`}>{p.title}</Link></h2><p>{p.description}</p><div className="project-meta"><span><Clock3 size={14}/> 3–8 weeks</span><span><Code2 size={14}/>{p.tech}</span></div><div className="tag-row"><span className="mini-tag">{p.career}</span></div><Link className="card-link" href={`/projects/${p.slug}`}>View complete brief <ArrowRight size={16}/></Link></article>)}</div></section></>;
}

export function ResourcesExplorer() {
  const [query,setQuery]=useState(""); const [category,setCategory]=useState("");
  const categories=[...new Set(resources.map(c=>c.category))];
  const filtered=resources.filter(r=>(!category||r.category===category)&&`${r.title} ${r.description}`.toLowerCase().includes(query.toLowerCase()));
  return <><Hero eyebrow="Resource library" title="Spend your learning time wisely." description="Search a curated starting library of official documentation, university courses, respected practice tools, and community recommendations."/><section className="section-tight container"><div className="resource-actions"><div><FilterBar query={query} setQuery={setQuery} placeholder="Search resources…" category={category} setCategory={setCategory} categories={categories}/></div><Link className="btn btn-primary" href="/resources/submit">Submit a resource</Link></div><div className="sort-line"><span>{filtered.length} resources</span><span>Sorted by: Featured first</span></div><div className="resource-directory">{filtered.sort((a,b)=>Number(b.featured)-Number(a.featured)).map(r=><article className="resource-card card" key={r.url}><div className="resource-card-head"><span className="resource-icon"><Star size={17}/></span><div>{r.featured&&<span className="pill">Featured</span>}<span className="pill free">Free</span></div></div><h2>{r.title}</h2><p>{r.description}</p><div className="resource-details"><span>{r.category}</span><span>{r.format}</span></div><div className="resource-card-actions"><a className="btn btn-secondary" href={r.url} target="_blank" rel="noopener noreferrer">Visit resource <ExternalLink size={15}/></a><button aria-label={`Bookmark ${r.title}`}><Bookmark size={18}/></button></div></article>)}</div></section></>;
}

export function RoadmapExplorer() {
  const [completed,setCompleted]=useState<number[]>([0]);
  const toggle=(i:number)=>setCompleted(v=>v.includes(i)?v.filter(x=>x!==i):[...v,i]);
  const pct=Math.round(completed.length/roadmapPhases.length*100);
  return <><Hero eyebrow="Personalized roadmap" title="A connected path from learning to applying." description="Browse freely as a visitor. Sign in to save statuses, notes, and the next actions suggested from your progress."/><section className="section-tight container roadmap-page"><aside className="roadmap-summary card"><span className="eyebrow">Software Engineering</span><h2>Your progress</h2><strong className="big-progress">{pct}%</strong><div className="progress-bar"><span style={{width:`${pct}%`}}/></div><p>{completed.length} of {roadmapPhases.length} phases touched</p><h3>Next three actions</h3><ol><li>Practice debugging with breakpoints</li><li>Write tests for one existing project</li><li>Sketch a small API contract</li></ol><Link className="btn btn-primary" href="/signup">Save my progress</Link></aside><div className="roadmap-list">{roadmapPhases.map((p,i)=><article className={`roadmap-step card ${completed.includes(i)?"complete":""}`} key={p[0]}><button aria-label={`Mark ${p[1]} completed`} onClick={()=>toggle(i)}>{completed.includes(i)?<CheckCircle2/>:<span>{p[0]}</span>}</button><div><span className="pill">{i<3?"Foundations":i<6?"Build":"Recruit"}</span><h2>{p[1]}</h2><p>{p[2]}</p><small>Estimated effort · {p[3]}</small></div></article>)}</div></section></>;
}

export function CommunityExplorer() {
  return <><Hero eyebrow="Student community" title="Specific questions. Generous answers." description="Share what you tried, add context, and help the next student make a better decision."/><section className="section-tight container"><div className="community-toolbar"><div className="filter-bar card"><label className="search-field"><Search/><input placeholder="Search discussions…"/></label></div><Link className="btn btn-primary" href="/login">Start a discussion</Link></div><div className="forum-layout"><div className="forum-list card">{[...discussions,...discussions].map((d,i)=><Link href={`/community/sample-${i+1}`} className="forum-row" key={i}><div className="forum-votes"><strong>{d.votes+i}</strong><span>votes</span></div><div><span className="pill">{d.category}</span><h2>{d.title}</h2><p>By {d.author} · Last activity {d.last}</p></div><span className="forum-replies"><MessageCircle size={16}/>{d.replies+i}</span></Link>)}</div><aside className="forum-aside card"><h2>Browse topics</h2>{["General Career Questions","Internship Applications","Interview Experiences","Resume and Portfolio","Project Ideas","Technical Interviews","Research Opportunities","Find Teammates"].map(c=><a href="#" key={c}>{c}</a>)}<div className="guideline-note"><strong>Build a useful community</strong><p>Be specific, protect privacy, and critique ideas—not people.</p></div></aside></div></section></>;
}

export function RecruitingPage() {
  const [season,setSeason]=useState(2);
  const seasons=[["January–April","Interview, follow up, and explore late-cycle roles."],["May–July","Build evidence, strengthen materials, and map target companies."],["August–October","Apply early while continuing projects and interview practice."],["November–December","Sustain the pipeline and consider startups, research, and local teams."]];
  return <><Hero eyebrow="Recruiting hub" title="Recruiting is a cycle, not a single deadline." description="Use typical windows as planning guidance—not guarantees. Company timelines differ and change every year."/><section className="section-tight container"><div className="season-tabs" role="tablist">{seasons.map((s,i)=><button role="tab" aria-selected={season===i} onClick={()=>setSeason(i)} key={s[0]}>{s[0]}</button>)}</div><div className="season-detail card"><div><span className="eyebrow">Typical focus</span><h2>{seasons[season][0]}</h2><p>{seasons[season][1]}</p></div><div className="season-actions">{["Update your target-company list","Apply to roles that fit most—not every—requirement","Prepare concise project explanations","Schedule one mock interview","Track every next action"].map((a,i)=><div key={a}><span>{i+1}</span><p>{a}</p></div>)}</div></div><div className="guide-grid">{["Finding opportunities","Reading job descriptions","Using referrals well","Career fairs","Avoiding scams","Handling rejection"].map((g,i)=><article className="card guide-card" key={g}><BriefcaseBusiness/><h2>{g}</h2><p>{["Search by adjacent titles, follow company career pages, and include local teams, labs, and nonprofits.","Treat requirements as signals. Apply when your evidence matches the core work, even if not every line.","Ask for perspective before asking for a referral. Make it easy for someone to say no.","Prepare a short introduction, research attending employers, and record follow-ups immediately.","Never pay for a job, verify sender domains, and be cautious with checks, equipment purchases, and sensitive data.","Record what you learned, keep applying, and avoid interpreting one process as a verdict on your potential."][i]}</p></article>)}</div></section></>;
}
